name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app for Windows
        run: npm run build

      - name: Upload .exe to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app for Linux
        run: npm run build

      - name: Upload AppImage to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*.AppImage
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
